import { BadRequestException, Body, Controller, ForbiddenException, Get, Inject, Optional, Param, Post, Put, Req } from "@nestjs/common";
import { AlertDestinationSchema, AlertRuleCreateSchema, AlertRuleSchema, AuthenticationPolicySchema, DataGovernancePolicySchema, DeliveryAttemptSchema, ExecutionNetworkPolicySchema, OrgPermissionSchema, OrganizationProfileSchema, ReportRunSchema, ReportScheduleCreateSchema, ReportScheduleSchema, SavedAnalyticsViewCreateSchema, SavedAnalyticsViewSchema, ServiceAccountCreateSchema, ServiceAccountSchema, ServiceAccountTokenResponseSchema, type OrgPermission } from "@berry/shared";
import { z } from "zod";
import { AUDIT_SERVICE, type AuditService } from "../audit/audit.service.ts";
import type { AuthenticatedRequest } from "../auth/auth.guard.ts";
import { ENTERPRISE_IDENTITY_REPOSITORY, type EnterpriseIdentityRepository } from "../identity/identity.repository.ts";
import { MANAGEMENT_SERVICE, type ManagementService } from "./management.service.ts";
const DestinationCreateSchema=z.object({kind:z.enum(["email","webhook"]),label:z.string().min(1),emailRecipients:z.array(z.string().email()).default([]),secret:z.string().min(8).optional()}).strict();
const ExecutionUpdateSchema=ExecutionNetworkPolicySchema.omit({tenantId:true,updatedAt:true}).strict();const AuthenticationUpdateSchema=AuthenticationPolicySchema.omit({tenantId:true,updatedAt:true}).strict();const DataUpdateSchema=DataGovernancePolicySchema.omit({tenantId:true,updatedAt:true}).strict();const ProfileUpdateSchema=OrganizationProfileSchema.omit({tenantId:true,domains:true,updatedAt:true}).strict();
@Controller("/v1/orgs/:tenantId")
export class ManagementController {
 constructor(@Inject(MANAGEMENT_SERVICE)private readonly service:ManagementService,@Inject(ENTERPRISE_IDENTITY_REPOSITORY)private readonly identity:EnterpriseIdentityRepository,@Optional()@Inject(AUDIT_SERVICE)private readonly audit?:AuditService){}
 @Get("/analytics/views")async views(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"usage:read");return z.array(SavedAnalyticsViewSchema).parse(await this.service.listViews(t,r.auth!.user.id));}
 @Post("/analytics/views")async createView(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Body()b:unknown){await this.require(r,t,"reports:write");const row=await this.service.createView(t,r.auth!.user.id,parse(SavedAnalyticsViewCreateSchema,b));await this.record(r,t,"saved-view-created",row.id,row);return SavedAnalyticsViewSchema.parse(row);}
 @Get("/reports/schedules")async schedules(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"reports:read");return z.array(ReportScheduleSchema).parse(await this.service.listSchedules(t));}
 @Post("/reports/schedules")async createSchedule(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Body()b:unknown){await this.require(r,t,"reports:write");const row=await this.service.createSchedule(t,parse(ReportScheduleCreateSchema,b));await this.record(r,t,"report-schedule-created",row.id,row);return ReportScheduleSchema.parse(row);}
 @Get("/reports/runs")async runs(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"reports:read");return z.array(ReportRunSchema).parse(await this.service.listRuns(t));}
 @Get("/alerts/destinations")async destinations(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"alerts:read");return z.array(AlertDestinationSchema).parse(await this.service.listDestinations(t));}
 @Post("/alerts/destinations")async createDestination(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Body()b:unknown){await this.require(r,t,"alerts:write");const row=await this.service.createDestination(t,parse(DestinationCreateSchema,b));await this.record(r,t,"alert-destination-created",row.id,row);return AlertDestinationSchema.parse(row);}
 @Get("/alerts/rules")async rules(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"alerts:read");return z.array(AlertRuleSchema).parse(await this.service.listRules(t));}
 @Post("/alerts/rules")async createRule(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Body()b:unknown){await this.require(r,t,"alerts:write");const row=await this.service.createRule(t,parse(AlertRuleCreateSchema,b));await this.record(r,t,"alert-rule-created",row.id,row);return AlertRuleSchema.parse(row);}
 @Get("/alerts/events")async events(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"alerts:read");return this.service.listAlertEvents(t);}
 @Get("/alerts/deliveries")async deliveries(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"alerts:read");return z.array(DeliveryAttemptSchema).parse(await this.service.listDeliveries(t));}
 @Get("/policies/execution")async execution(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"guardrails:read");return this.service.getExecution(t);}
 @Put("/policies/execution")async setExecution(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Body()b:unknown){await this.require(r,t,"guardrails:write");const row=await this.service.setExecution(t,parse(ExecutionUpdateSchema,b));await this.record(r,t,"execution-policy-updated",t,row);return row;}
 @Get("/policies/authentication")async authentication(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"auth_policy:read");return this.service.getAuthentication(t);}
 @Put("/policies/authentication")async setAuthentication(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Body()b:unknown){await this.require(r,t,"auth_policy:write");const row=await this.service.setAuthentication(t,parse(AuthenticationUpdateSchema,b));await this.record(r,t,"authentication-policy-updated",t,row);return row;}
 @Get("/policies/data")async data(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"data_policy:read");return this.service.getData(t);}
 @Put("/policies/data")async setData(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Body()b:unknown){await this.require(r,t,"data_policy:write");const row=await this.service.setData(t,parse(DataUpdateSchema,b));await this.record(r,t,"data-policy-updated",t,row);return row;}
 @Get("/profile")async profile(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"org_settings:read");return this.service.getProfile(t);}
 @Put("/profile")async setProfile(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Body()b:unknown){await this.require(r,t,"org_settings:write");const row=await this.service.setProfile(t,parse(ProfileUpdateSchema,b));await this.record(r,t,"organization-profile-updated",t,row);return row;}
 @Get("/service-accounts")async accounts(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string){await this.require(r,t,"service_accounts:read");return z.array(ServiceAccountSchema).parse(await this.service.listServiceAccounts(t));}
 @Post("/service-accounts")async createAccount(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Body()b:unknown){await this.require(r,t,"service_accounts:write");const row=await this.service.createServiceAccount(t,r.auth!.user.id,parse(ServiceAccountCreateSchema,b));await this.record(r,t,"service-account-created",row.account.id,row.account);return ServiceAccountTokenResponseSchema.parse(row);}
 @Post("/service-accounts/:id/rotate")async rotate(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Param("id")id:string){await this.require(r,t,"service_accounts:write");const row=await this.service.rotateServiceAccount(t,r.auth!.user.id,id);await this.record(r,t,"service-account-rotated",id,row.account);return row;}
 @Post("/service-accounts/:id/revoke")async revoke(@Req()r:AuthenticatedRequest,@Param("tenantId")t:string,@Param("id")id:string){await this.require(r,t,"service_accounts:write");const row=await this.service.revokeServiceAccount(t,id);await this.record(r,t,"service-account-revoked",id,row);return row;}
 private async require(r:AuthenticatedRequest,t:string,p:OrgPermission){OrgPermissionSchema.parse(p);if(!await this.identity.authorize(r.auth!.user.id,t,p))throw new ForbiddenException(`Missing organization permission: ${p}`);} private record(r:AuthenticatedRequest,t:string,a:string,id:string,after:unknown){return this.audit?.append({tenantId:t,actorUserId:r.auth?.user.id??null,category:"management",action:a,targetType:"management_resource",targetId:id,after:after as never,metadata:{surface:"admin-api"}});}
}
function parse<T extends z.ZodTypeAny>(s:T,v:unknown):z.infer<T>{const r=s.safeParse(v);if(!r.success)throw new BadRequestException(r.error.flatten());return r.data;}
