import { createHash, randomBytes, randomUUID } from "node:crypto";
import {
  AlertDestinationSchema, AlertEventSchema, AlertRuleSchema, AuthenticationPolicySchema, DataGovernancePolicySchema,
  DeliveryAttemptSchema, ExecutionNetworkPolicySchema, OrganizationProfileSchema, ReportRunSchema, ReportScheduleSchema,
  SavedAnalyticsViewSchema, ServiceAccountSchema, ServiceAccountTokenResponseSchema,
  type AlertDestination, type AlertEvent, type AlertRule, type AlertRuleCreate, type AuthenticationPolicy,
  type DataGovernancePolicy, type DeliveryAttempt, type ExecutionNetworkPolicy, type OrganizationProfile,
  type ReportRun, type ReportSchedule, type ReportScheduleCreate, type SavedAnalyticsView, type SavedAnalyticsViewCreate,
  type ServiceAccount, type ServiceAccountCreate, type ServiceAccountTokenResponse,
} from "@berry/shared";
import type { CloudDatabaseService } from "../db/cloud-database.service.ts";

export const MANAGEMENT_SERVICE = Symbol("MANAGEMENT_SERVICE");
export type DestinationInput = { kind:"email"|"webhook";label:string;emailRecipients:string[];secret?:string|undefined };
type PolicyInput<T extends {tenantId:string;updatedAt:string}> = Omit<T,"tenantId"|"updatedAt">;

export interface ManagementRepository {
  listViews(tenantId:string,userId:string):Promise<SavedAnalyticsView[]>; createView(tenantId:string,userId:string,input:SavedAnalyticsViewCreate):Promise<SavedAnalyticsView>;
  listSchedules(tenantId:string):Promise<ReportSchedule[]>; createSchedule(tenantId:string,input:ReportScheduleCreate):Promise<ReportSchedule>; listRuns(tenantId:string):Promise<ReportRun[]>;
  listDestinations(tenantId:string):Promise<AlertDestination[]>; createDestination(tenantId:string,input:DestinationInput):Promise<AlertDestination>;
  listRules(tenantId:string):Promise<AlertRule[]>; createRule(tenantId:string,input:AlertRuleCreate):Promise<AlertRule>; listAlertEvents(tenantId:string):Promise<AlertEvent[]>; listDeliveries(tenantId:string):Promise<DeliveryAttempt[]>;
  getExecution(tenantId:string):Promise<ExecutionNetworkPolicy>; setExecution(tenantId:string,input:PolicyInput<ExecutionNetworkPolicy>):Promise<ExecutionNetworkPolicy>;
  getAuthentication(tenantId:string):Promise<AuthenticationPolicy>; setAuthentication(tenantId:string,input:PolicyInput<AuthenticationPolicy>):Promise<AuthenticationPolicy>;
  getData(tenantId:string):Promise<DataGovernancePolicy>; setData(tenantId:string,input:PolicyInput<DataGovernancePolicy>):Promise<DataGovernancePolicy>;
  getProfile(tenantId:string):Promise<OrganizationProfile>; setProfile(tenantId:string,input:Omit<OrganizationProfile,"tenantId"|"domains"|"updatedAt" >):Promise<OrganizationProfile>;
  listServiceAccounts(tenantId:string):Promise<ServiceAccount[]>; createServiceAccount(tenantId:string,userId:string,input:ServiceAccountCreate,tokenHash:string,last4:string):Promise<ServiceAccount>; revokeServiceAccount(tenantId:string,id:string):Promise<ServiceAccount>;
}

export class ManagementService {
  constructor(private readonly repository:ManagementRepository){}
  listViews(t:string,u:string){return this.repository.listViews(t,u);} createView(t:string,u:string,i:SavedAnalyticsViewCreate){return this.repository.createView(t,u,i);}
  listSchedules(t:string){return this.repository.listSchedules(t);} createSchedule(t:string,i:ReportScheduleCreate){return this.repository.createSchedule(t,i);} listRuns(t:string){return this.repository.listRuns(t);}
  listDestinations(t:string){return this.repository.listDestinations(t);} createDestination(t:string,i:DestinationInput){return this.repository.createDestination(t,i);}
  listRules(t:string){return this.repository.listRules(t);} createRule(t:string,i:AlertRuleCreate){return this.repository.createRule(t,i);} listAlertEvents(t:string){return this.repository.listAlertEvents(t);} listDeliveries(t:string){return this.repository.listDeliveries(t);}
  getExecution(t:string){return this.repository.getExecution(t);} setExecution(t:string,i:PolicyInput<ExecutionNetworkPolicy>){return this.repository.setExecution(t,i);}
  getAuthentication(t:string){return this.repository.getAuthentication(t);} setAuthentication(t:string,i:PolicyInput<AuthenticationPolicy>){return this.repository.setAuthentication(t,i);}
  getData(t:string){return this.repository.getData(t);} setData(t:string,i:PolicyInput<DataGovernancePolicy>){return this.repository.setData(t,i);}
  getProfile(t:string){return this.repository.getProfile(t);} setProfile(t:string,i:Omit<OrganizationProfile,"tenantId"|"domains"|"updatedAt">){return this.repository.setProfile(t,i);}
  listServiceAccounts(t:string){return this.repository.listServiceAccounts(t);}
  async createServiceAccount(t:string,u:string,i:ServiceAccountCreate):Promise<ServiceAccountTokenResponse>{const token=`berry_sa_${randomBytes(32).toString("base64url")}`;const account=await this.repository.createServiceAccount(t,u,i,createHash("sha256").update(token).digest("hex"),token.slice(-4));return ServiceAccountTokenResponseSchema.parse({account,token});}
  async rotateServiceAccount(t:string,u:string,id:string):Promise<ServiceAccountTokenResponse>{const existing=(await this.repository.listServiceAccounts(t)).find((row)=>row.id===id);if(!existing)throw new Error("Service account not found");await this.repository.revokeServiceAccount(t,id);return this.createServiceAccount(t,u,{name:`${existing.name} rotated`,permissions:existing.permissions,departmentId:existing.departmentId,resourceRestrictions:existing.resourceRestrictions,expiresAt:existing.expiresAt});}
  revokeServiceAccount(t:string,id:string){return this.repository.revokeServiceAccount(t,id);}
}

export class InMemoryManagementRepository implements ManagementRepository {
  private rows=new Map<string,unknown[]>(); private policies=new Map<string,unknown>();
  private list<T>(t:string,k:string){return (this.rows.get(`${t}:${k}`)??[]) as T[];} private add<T>(t:string,k:string,row:T){this.rows.set(`${t}:${k}`,[...this.list<T>(t,k),row]);return row;}
  async listViews(t:string,u:string){return this.list<SavedAnalyticsView>(t,"views").filter((r)=>r.visibility==="tenant"||r.ownerUserId===u);} async createView(t:string,u:string,i:SavedAnalyticsViewCreate){const n=now();return this.add(t,"views",SavedAnalyticsViewSchema.parse({...i,id:randomUUID(),tenantId:t,ownerUserId:u,createdAt:n,updatedAt:n}));}
  async listSchedules(t:string){return this.list<ReportSchedule>(t,"schedules");} async createSchedule(t:string,i:ReportScheduleCreate){const n=now();return this.add(t,"schedules",ReportScheduleSchema.parse({...i,id:randomUUID(),tenantId:t,status:"active",nextRunAt:n,lastRunAt:null,createdAt:n,updatedAt:n}));} async listRuns(t:string){return this.list<ReportRun>(t,"runs");}
  async listDestinations(t:string){return this.list<AlertDestination>(t,"destinations");} async createDestination(t:string,i:DestinationInput){const n=now();return this.add(t,"destinations",AlertDestinationSchema.parse({id:randomUUID(),tenantId:t,kind:i.kind,label:i.label,configured:i.kind==="email"?i.emailRecipients.length>0:Boolean(i.secret),emailRecipients:i.emailRecipients,createdAt:n,updatedAt:n}));}
  async listRules(t:string){return this.list<AlertRule>(t,"rules");} async createRule(t:string,i:AlertRuleCreate){const n=now();return this.add(t,"rules",AlertRuleSchema.parse({...i,id:randomUUID(),tenantId:t,createdAt:n,updatedAt:n}));} async listAlertEvents(t:string){return this.list<AlertEvent>(t,"events");} async listDeliveries(t:string){return this.list<DeliveryAttempt>(t,"deliveries");}
  async getExecution(t:string){return this.policy(t,"execution",ExecutionNetworkPolicySchema,executionDefaults(t));} async setExecution(t:string,i:PolicyInput<ExecutionNetworkPolicy>){return this.setPolicy(t,"execution",ExecutionNetworkPolicySchema,{...i,tenantId:t,updatedAt:now()});}
  async getAuthentication(t:string){return this.policy(t,"authentication",AuthenticationPolicySchema,authenticationDefaults(t));} async setAuthentication(t:string,i:PolicyInput<AuthenticationPolicy>){return this.setPolicy(t,"authentication",AuthenticationPolicySchema,{...i,tenantId:t,updatedAt:now()});}
  async getData(t:string){return this.policy(t,"data",DataGovernancePolicySchema,dataDefaults(t));} async setData(t:string,i:PolicyInput<DataGovernancePolicy>){return this.setPolicy(t,"data",DataGovernancePolicySchema,{...i,tenantId:t,updatedAt:now()});}
  async getProfile(t:string){return this.policy(t,"profile",OrganizationProfileSchema,profileDefaults(t));} async setProfile(t:string,i:Omit<OrganizationProfile,"tenantId"|"domains"|"updatedAt">){const current=await this.getProfile(t);return this.setPolicy(t,"profile",OrganizationProfileSchema,{...i,tenantId:t,domains:current.domains,updatedAt:now()});}
  async listServiceAccounts(t:string){return this.list<ServiceAccount>(t,"accounts");} async createServiceAccount(t:string,_u:string,i:ServiceAccountCreate,_h:string,last4:string){const n=now();return this.add(t,"accounts",ServiceAccountSchema.parse({...i,id:randomUUID(),tenantId:t,status:"active",departmentId:i.departmentId??null,expiresAt:i.expiresAt??null,lastUsedAt:null,tokenLast4:last4,createdAt:n,updatedAt:n}));} async revokeServiceAccount(t:string,id:string){const rows=this.list<ServiceAccount>(t,"accounts");const index=rows.findIndex((r)=>r.id===id);if(index<0)throw new Error("Service account not found");rows[index]=ServiceAccountSchema.parse({...rows[index],status:"revoked",updatedAt:now()});this.rows.set(`${t}:accounts`,rows);return rows[index]!;}
  private policy<T>(t:string,k:string,s:{parse(v:unknown):T},d:T){return s.parse(this.policies.get(`${t}:${k}`)??d);} private setPolicy<T>(t:string,k:string,s:{parse(v:unknown):T},v:unknown){const row=s.parse(v);this.policies.set(`${t}:${k}`,row);return row;}
}

export class PostgresManagementRepository implements ManagementRepository {
  constructor(private readonly database:CloudDatabaseService){}
  listViews(t:string,u:string){return this.database.withTenant(t,async db=>(await db.query<any>("SELECT * FROM saved_analytics_views WHERE tenant_id=$1::uuid AND (visibility='tenant' OR owner_user_id=$2::uuid) ORDER BY updated_at DESC",[t,u])).map(viewRow));}
  createView(t:string,u:string,i:SavedAnalyticsViewCreate){return this.database.withTenant(t,async db=>viewRow((await db.query<any>("INSERT INTO saved_analytics_views (tenant_id,owner_user_id,name,filters,visibility) VALUES ($1::uuid,$2::uuid,$3,$4::jsonb,$5) RETURNING *",[t,u,i.name,JSON.stringify(i.filters),i.visibility]))[0]));}
  listSchedules(t:string){return this.database.withTenant(t,async db=>(await db.query<any>("SELECT * FROM report_schedules WHERE tenant_id=$1::uuid ORDER BY updated_at DESC",[t])).map(scheduleRow));}
  createSchedule(t:string,i:ReportScheduleCreate){return this.database.withTenant(t,async db=>scheduleRow((await db.query<any>("INSERT INTO report_schedules (tenant_id,saved_view_id,name,format,cadence,timezone,recipients,next_run_at) VALUES ($1::uuid,$2::uuid,$3,$4,$5,$6,$7::jsonb,now()) RETURNING *",[t,i.savedViewId,i.name,i.format,i.cadence,i.timezone,JSON.stringify(i.recipients)]))[0]));}
  listRuns(t:string){return this.database.withTenant(t,async db=>(await db.query<any>("SELECT * FROM report_runs WHERE tenant_id=$1::uuid ORDER BY created_at DESC LIMIT 100",[t])).map(runRow));}
  listDestinations(t:string){return this.database.withTenant(t,async db=>(await db.query<any>("SELECT * FROM alert_destinations WHERE tenant_id=$1::uuid ORDER BY label",[t])).map(destinationRow));}
  createDestination(t:string,i:DestinationInput){return this.database.withTenant(t,async db=>destinationRow((await db.query<any>("INSERT INTO alert_destinations (tenant_id,kind,label,email_recipients,secret_ref,configured) VALUES ($1::uuid,$2,$3,$4::jsonb,$5,$6) RETURNING *",[t,i.kind,i.label,JSON.stringify(i.emailRecipients),i.secret?`sha256:${createHash("sha256").update(i.secret).digest("hex")}`:null,i.kind==="email"?i.emailRecipients.length>0:Boolean(i.secret)]))[0]));}
  listRules(t:string){return this.database.withTenant(t,async db=>(await db.query<any>("SELECT * FROM alert_rules WHERE tenant_id=$1::uuid ORDER BY name",[t])).map(ruleRow));}
  createRule(t:string,i:AlertRuleCreate){return this.database.withTenant(t,async db=>ruleRow((await db.query<any>("INSERT INTO alert_rules (tenant_id,name,signal,enabled,scope_type,scope_id,threshold,window_minutes,destination_ids) VALUES ($1::uuid,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) RETURNING *",[t,i.name,i.signal,i.enabled,i.scopeType??null,i.scopeId??null,i.threshold,i.windowMinutes,JSON.stringify(i.destinationIds)]))[0]));}
  listAlertEvents(t:string){return this.database.withTenant(t,async db=>(await db.query<any>("SELECT * FROM alert_events WHERE tenant_id=$1::uuid ORDER BY created_at DESC LIMIT 100",[t])).map(eventRow));} listDeliveries(t:string){return this.database.withTenant(t,async db=>(await db.query<any>("SELECT * FROM delivery_attempts WHERE tenant_id=$1::uuid ORDER BY created_at DESC LIMIT 100",[t])).map(deliveryRow));}
  getExecution(t:string){return this.getJsonPolicy(t,"execution_network_policies",ExecutionNetworkPolicySchema,executionDefaults(t));} setExecution(t:string,i:PolicyInput<ExecutionNetworkPolicy>){return this.setJsonPolicy(t,"execution_network_policies",ExecutionNetworkPolicySchema,{...i,tenantId:t,updatedAt:now()});}
  getAuthentication(t:string){return this.getJsonPolicy(t,"authentication_policies",AuthenticationPolicySchema,authenticationDefaults(t));} setAuthentication(t:string,i:PolicyInput<AuthenticationPolicy>){return this.setJsonPolicy(t,"authentication_policies",AuthenticationPolicySchema,{...i,tenantId:t,updatedAt:now()});}
  getData(t:string){return this.getJsonPolicy(t,"data_governance_policies",DataGovernancePolicySchema,dataDefaults(t));} setData(t:string,i:PolicyInput<DataGovernancePolicy>){return this.setJsonPolicy(t,"data_governance_policies",DataGovernancePolicySchema,{...i,tenantId:t,updatedAt:now()});}
  getProfile(t:string){return this.database.withTenant(t,async db=>{const r=(await db.query<any>("SELECT p.*,t.name tenant_name,t.slug tenant_slug,t.deployment_mode,NULLIF(t.settings->>'region','') region FROM organization_profiles p RIGHT JOIN tenants t ON t.id=p.tenant_id WHERE t.id=$1::uuid",[t]))[0];const domains=(await db.query<any>("SELECT * FROM organization_domains WHERE tenant_id=$1::uuid ORDER BY domain",[t])).map(domainRow);return r?profileRow(r,domains):profileDefaults(t);});}
  setProfile(t:string,i:Omit<OrganizationProfile,"tenantId"|"domains"|"updatedAt">){return this.database.withTenant(t,async db=>{await db.execute("UPDATE tenants SET name=$2,slug=$3,updated_at=now() WHERE id=$1::uuid",[t,i.name,i.slug]);await db.execute(`INSERT INTO organization_profiles (tenant_id,logo_url,timezone,language,support_email,security_email,announcements,terms_url,privacy_url,branding) VALUES ($1::uuid,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10::jsonb) ON CONFLICT (tenant_id) DO UPDATE SET logo_url=excluded.logo_url,timezone=excluded.timezone,language=excluded.language,support_email=excluded.support_email,security_email=excluded.security_email,announcements=excluded.announcements,terms_url=excluded.terms_url,privacy_url=excluded.privacy_url,branding=excluded.branding,updated_at=now()`,[t,i.logoUrl,i.timezone,i.language,i.supportEmail,i.securityEmail,JSON.stringify(i.announcements),i.termsUrl,i.privacyUrl,JSON.stringify(i.branding)]);return this.getProfile(t);});}
  listServiceAccounts(t:string){return this.database.withTenant(t,async db=>(await db.query<any>("SELECT * FROM service_accounts WHERE tenant_id=$1::uuid ORDER BY created_at DESC",[t])).map(accountRow));}
  createServiceAccount(t:string,u:string,i:ServiceAccountCreate,h:string,last4:string){return this.database.withTenant(t,async db=>accountRow((await db.query<any>("INSERT INTO service_accounts (tenant_id,name,permissions,department_id,resource_restrictions,token_hash,token_last4,expires_at,created_by) VALUES ($1::uuid,$2,$3::jsonb,$4::uuid,$5::jsonb,$6,$7,$8,$9::uuid) RETURNING *",[t,i.name,JSON.stringify(i.permissions),i.departmentId??null,JSON.stringify(i.resourceRestrictions),h,last4,i.expiresAt??null,u]))[0]));}
  revokeServiceAccount(t:string,id:string){return this.database.withTenant(t,async db=>accountRow((await db.query<any>("UPDATE service_accounts SET status='revoked',token_hash=encode(digest(gen_random_uuid()::text,'sha256'),'hex'),updated_at=now() WHERE tenant_id=$1::uuid AND id=$2::uuid RETURNING *",[t,id]))[0]));}
  private getJsonPolicy<T>(t:string,table:string,schema:{parse(value:unknown):T},fallback:T){return this.database.withTenant(t,async db=>{const row=(await db.query<{policy:unknown}>(`SELECT policy FROM ${table} WHERE tenant_id=$1::uuid`,[t]))[0];return row?schema.parse(row.policy):fallback;});}
  private setJsonPolicy<T>(t:string,table:string,schema:{parse(value:unknown):T},value:unknown){const parsed=schema.parse(value);return this.database.withTenant(t,async db=>{await db.execute(`INSERT INTO ${table}(tenant_id,policy) VALUES($1::uuid,$2::jsonb) ON CONFLICT(tenant_id) DO UPDATE SET policy=excluded.policy,updated_at=now()`,[t,JSON.stringify(parsed)]);return parsed;});}
}

const executionDefaults=(t:string)=>ExecutionNetworkPolicySchema.parse({tenantId:t,sandboxEnabled:true,codeExecutionEnabled:true,approvalRequired:true,outboundNetwork:"allowlist",allowedDomains:[],blockedDomains:[],allowedToolClasses:[],maxRunSeconds:900,maxConcurrency:5,requestsPerMinute:60,tokenQuota:null,sandboxMinuteQuota:null,updatedAt:now()});
const authenticationDefaults=(t:string)=>AuthenticationPolicySchema.parse({tenantId:t,mfaRequired:false,sessionMaxAgeMinutes:10080,idleTimeoutMinutes:120,trustedDevicesAllowed:true,allowedLoginMethods:["password","oidc","saml"],allowedDomains:[],emergencyLocalOwnerEnabled:true,updatedAt:now()});
const dataDefaults=(t:string)=>DataGovernancePolicySchema.parse({tenantId:t,conversationRetentionDays:365,temporaryChatHours:24,retentionByDataType:{conversation:365,files:365},residency:"deployment-default",piiFilterMode:"warn",credentialFilterMode:"block",moderationHookConfigured:false,legalHoldEnabled:false,updatedAt:now()});
const profileDefaults=(t:string)=>OrganizationProfileSchema.parse({tenantId:t,name:"Berry organization",slug:t,logoUrl:null,timezone:"UTC",language:"en",supportEmail:null,securityEmail:null,deploymentMode:"self-hosted",region:null,announcements:[],termsUrl:null,privacyUrl:null,branding:{},domains:[],updatedAt:now()});
function now(){return new Date().toISOString();} function iso(v:any){return v instanceof Date?v.toISOString():new Date(v).toISOString();}
const viewRow=(r:any)=>SavedAnalyticsViewSchema.parse({id:r.id,tenantId:r.tenant_id,name:r.name,ownerUserId:r.owner_user_id,filters:r.filters,visibility:r.visibility,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)});
const scheduleRow=(r:any)=>ReportScheduleSchema.parse({id:r.id,tenantId:r.tenant_id,name:r.name,savedViewId:r.saved_view_id,format:r.format,cadence:r.cadence,timezone:r.timezone,recipients:r.recipients,status:r.status,nextRunAt:r.next_run_at?iso(r.next_run_at):null,lastRunAt:r.last_run_at?iso(r.last_run_at):null,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)});
const runRow=(r:any)=>ReportRunSchema.parse({id:r.id,tenantId:r.tenant_id,scheduleId:r.schedule_id,windowKey:r.window_key,status:r.status,artifactRef:r.artifact_ref,error:r.error,startedAt:r.started_at?iso(r.started_at):null,completedAt:r.completed_at?iso(r.completed_at):null,createdAt:iso(r.created_at)});
const destinationRow=(r:any)=>AlertDestinationSchema.parse({id:r.id,tenantId:r.tenant_id,kind:r.kind,label:r.label,configured:r.configured,emailRecipients:r.email_recipients,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)});
const ruleRow=(r:any)=>AlertRuleSchema.parse({id:r.id,tenantId:r.tenant_id,name:r.name,signal:r.signal,enabled:r.enabled,scopeType:r.scope_type??undefined,scopeId:r.scope_id??undefined,threshold:Number(r.threshold),windowMinutes:r.window_minutes,destinationIds:r.destination_ids,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)});
const eventRow=(r:any)=>AlertEventSchema.parse({id:r.id,tenantId:r.tenant_id,ruleId:r.rule_id,windowKey:r.window_key,observed:Number(r.observed),baseline:r.baseline===null?null:Number(r.baseline),status:r.status,createdAt:iso(r.created_at)});
const deliveryRow=(r:any)=>DeliveryAttemptSchema.parse({id:r.id,tenantId:r.tenant_id,alertEventId:r.alert_event_id,reportRunId:r.report_run_id,destinationId:r.destination_id,attempt:r.attempt,status:r.status,providerMessageId:r.provider_message_id,error:r.error,createdAt:iso(r.created_at)});
const domainRow=(r:any)=>({id:r.id,domain:r.domain,status:r.status,customDomain:r.custom_domain,verifiedAt:r.verified_at?iso(r.verified_at):null});
const profileRow=(r:any,d:any[])=>OrganizationProfileSchema.parse({tenantId:r.tenant_id??r.id,name:r.tenant_name,slug:r.tenant_slug,logoUrl:r.logo_url??null,timezone:r.timezone??"UTC",language:r.language??"en",supportEmail:r.support_email??null,securityEmail:r.security_email??null,deploymentMode:r.deployment_mode,region:r.region??null,announcements:r.announcements??[],termsUrl:r.terms_url??null,privacyUrl:r.privacy_url??null,branding:r.branding??{},domains:d,updatedAt:iso(r.updated_at)});
const accountRow=(r:any)=>ServiceAccountSchema.parse({id:r.id,tenantId:r.tenant_id,name:r.name,status:r.status,permissions:r.permissions,departmentId:r.department_id,resourceRestrictions:r.resource_restrictions,expiresAt:r.expires_at?iso(r.expires_at):null,lastUsedAt:r.last_used_at?iso(r.last_used_at):null,tokenLast4:r.token_last4,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)});
