import { BadRequestException, Body, Controller, Delete, ForbiddenException, Get, Inject, Param, Patch, Post, Req } from "@nestjs/common";
import { OrgCapabilityAssignmentSchema, type OrgPermission } from "@berry/shared";
import { z } from "zod";
import type { AuthenticatedRequest } from "../auth/auth.guard.ts";
import { ENTERPRISE_IDENTITY_REPOSITORY, type EnterpriseIdentityRepository } from "../identity/identity.repository.ts";
import { AUDIT_SERVICE, type AuditService } from "../audit/audit.service.ts";
import { ORGANIZATION_CAPABILITIES, OrganizationCapabilitiesService } from "./organization-capabilities.service.ts";

const UpsertSchema=z.object({kind:z.enum(["skill","mcp"]),capabilityId:z.string().min(1),name:z.string().min(1),description:z.string().optional(),assignment:OrgCapabilityAssignmentSchema,allowUserDisable:z.boolean().optional(),contentHash:z.string().nullable().optional(),config:z.record(z.unknown()).optional()}).strict();
@Controller("/v1/orgs/:tenantId/capabilities")
export class OrganizationCapabilitiesController {
  constructor(@Inject(ORGANIZATION_CAPABILITIES) private readonly capabilities:OrganizationCapabilitiesService,@Inject(ENTERPRISE_IDENTITY_REPOSITORY) private readonly identity:EnterpriseIdentityRepository,@Inject(AUDIT_SERVICE) private readonly audit:AuditService){}
  @Get() async list(@Req() req:AuthenticatedRequest,@Param("tenantId") tenantId:string){await this.allow(req,tenantId,"skills:read");return this.capabilities.list(tenantId);}
  @Post() async upsert(@Req() req:AuthenticatedRequest,@Param("tenantId") tenantId:string,@Body() body:unknown){const input=parse(UpsertSchema,body);await this.allow(req,tenantId,input.kind==="skill"?"skills:write":"mcp:write");const result=await this.capabilities.upsert(tenantId,input as never);await this.audit.append({tenantId,actorUserId:req.auth!.user.id,category:"capabilities",action:"organization-capability-upserted",targetType:input.kind,targetId:result.capabilityId,after:result as never,metadata:{assignment:result.assignment,contentHash:result.contentHash}});return result;}
  @Delete(":id") async remove(@Req() req:AuthenticatedRequest,@Param("tenantId") tenantId:string,@Param("id") id:string){const record=(await this.capabilities.list(tenantId)).find((item)=>item.id===id);if(!record)return{ok:false};await this.allow(req,tenantId,record.kind==="skill"?"skills:write":"mcp:write");const result=await this.capabilities.remove(tenantId,id);await this.audit.append({tenantId,actorUserId:req.auth!.user.id,category:"capabilities",action:"organization-capability-deleted",targetType:record.kind,targetId:record.capabilityId,before:record as never,metadata:{assignment:record.assignment,contentHash:record.contentHash}});return result;}
  @Get("settings/personal-additions") async settings(@Req() req:AuthenticatedRequest,@Param("tenantId") tenantId:string){await this.allow(req,tenantId,"skills:read");return this.capabilities.settings(tenantId);}
  @Patch("settings/personal-additions") async updateSettings(@Req() req:AuthenticatedRequest,@Param("tenantId") tenantId:string,@Body() body:unknown){await this.allow(req,tenantId,"skills:write");await this.allow(req,tenantId,"mcp:write");const before=await this.capabilities.settings(tenantId);const result=await this.capabilities.updateSettings(tenantId,parse(z.object({skills:z.boolean(),mcp:z.boolean()}).strict(),body));await this.audit.append({tenantId,actorUserId:req.auth!.user.id,category:"capabilities",action:"personal-addition-policy-updated",targetType:"organization",targetId:tenantId,before:before as never,after:result as never,metadata:{}});return result;}
  @Get("effective/me") async effective(@Req() req:AuthenticatedRequest,@Param("tenantId") tenantId:string){await this.allow(req,tenantId,"skills:read");return (await this.capabilities.effective(tenantId,req.auth!.user.id)).rows;}
  @Patch("effective/me/:kind/:capabilityId") async override(@Req() req:AuthenticatedRequest,@Param("tenantId") tenantId:string,@Param("kind") kind:string,@Param("capabilityId") id:string,@Body() body:unknown){const parsedKind=z.enum(["skill","mcp"]).parse(kind);await this.allow(req,tenantId,parsedKind==="mcp"?"mcp:read":"skills:read");const effective=(await this.capabilities.effective(tenantId,req.auth!.user.id)).rows.find((item)=>item.kind===parsedKind&&item.capabilityId===id);if(!effective||effective.locked)throw new ForbiddenException("This organization capability is locked");return this.capabilities.setOverride(tenantId,req.auth!.user.id,parsedKind,id,parse(z.object({enabled:z.boolean()}).strict(),body).enabled);}
  private async allow(req:AuthenticatedRequest,tenantId:string,permission:OrgPermission){if(!await this.identity.authorize(req.auth!.user.id,tenantId,permission))throw new ForbiddenException(`Missing organization permission: ${permission}`);}
}
function parse<T extends z.ZodTypeAny>(schema:T,body:unknown):z.infer<T>{const result=schema.safeParse(body);if(!result.success)throw new BadRequestException(result.error.flatten());return result.data;}
