/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as SettingsTabRouteImport } from './routes/settings.$tab'
import { Route as PlatformTabRouteImport } from './routes/platform.$tab'
import { Route as LibraryTabRouteImport } from './routes/library.$tab'
import { Route as AdminTabRouteImport } from './routes/admin.$tab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTabRoute = SettingsTabRouteImport.update({
  id: '/settings/$tab',
  path: '/settings/$tab',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformTabRoute = PlatformTabRouteImport.update({
  id: '/platform/$tab',
  path: '/platform/$tab',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryTabRoute = LibraryTabRouteImport.update({
  id: '/library/$tab',
  path: '/library/$tab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTabRoute = AdminTabRouteImport.update({
  id: '/admin/$tab',
  path: '/admin/$tab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$tab': typeof AdminTabRoute
  '/library/$tab': typeof LibraryTabRoute
  '/platform/$tab': typeof PlatformTabRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$tab': typeof AdminTabRoute
  '/library/$tab': typeof LibraryTabRoute
  '/platform/$tab': typeof PlatformTabRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/$tab': typeof AdminTabRoute
  '/library/$tab': typeof LibraryTabRoute
  '/platform/$tab': typeof PlatformTabRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/$tab'
    | '/library/$tab'
    | '/platform/$tab'
    | '/settings/$tab'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/$tab'
    | '/library/$tab'
    | '/platform/$tab'
    | '/settings/$tab'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/admin/$tab'
    | '/library/$tab'
    | '/platform/$tab'
    | '/settings/$tab'
    | '/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminTabRoute: typeof AdminTabRoute
  LibraryTabRoute: typeof LibraryTabRoute
  PlatformTabRoute: typeof PlatformTabRoute
  SettingsTabRoute: typeof SettingsTabRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$tab': {
      id: '/settings/$tab'
      path: '/settings/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof SettingsTabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/$tab': {
      id: '/platform/$tab'
      path: '/platform/$tab'
      fullPath: '/platform/$tab'
      preLoaderRoute: typeof PlatformTabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$tab': {
      id: '/library/$tab'
      path: '/library/$tab'
      fullPath: '/library/$tab'
      preLoaderRoute: typeof LibraryTabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$tab': {
      id: '/admin/$tab'
      path: '/admin/$tab'
      fullPath: '/admin/$tab'
      preLoaderRoute: typeof AdminTabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminTabRoute: AdminTabRoute,
  LibraryTabRoute: LibraryTabRoute,
  PlatformTabRoute: PlatformTabRoute,
  SettingsTabRoute: SettingsTabRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
