apiVersion: v1
kind: Service
metadata:
  name: {{ include "berry-platform.name" . }}-api
  labels:
    {{- include "berry-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "berry-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "berry-platform.name" . }}-web
  labels:
    {{- include "berry-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "berry-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.web.port }}
