apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "berry-platform.name" . }}-web
  labels:
    {{- include "berry-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "berry-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "berry-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["apps/web/node_modules/.bin/srvx", "--prod", "-s", "../client", "apps/web/dist/server/server.js"]
          ports:
            - containerPort: {{ .Values.web.port }}
          envFrom:
            - configMapRef:
                name: {{ include "berry-platform.name" . }}-config
          env:
            - name: PORT
              value: {{ .Values.web.port | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            periodSeconds: 10
