import * as React from "react";
import { Download, X } from "lucide-react";
import type { UsageAnalyticsQuery, UsageRequestDetail } from "@berry/shared";
import { AsyncState, Button, DataTable, DetailDrawer, DualTrend, Input, ManagementPage, MetricGrid, Section, StatusPill, Toolbar, formatMoney, formatNumber } from "./management-primitives";
import { useResource, type ManagementScreenProps } from "./management-context";

const VIEWS = ["overview", "people", "models", "agents", "requests", "reports"] as const;
type View = typeof VIEWS[number];

export function AnalyticsScreen({ client, config, tenantId, permissions }: ManagementScreenProps) {
  const search = React.useMemo(() => new URLSearchParams(location.search), []);
  const [view, setView] = React.useState<View>((VIEWS.find((item) => item === search.get("view")) ?? "overview"));
  const [range, setRange] = React.useState({
    from: (search.get("from") ?? new Date(Date.now() - 30 * 86_400_000).toISOString()).slice(0, 10),
    to: (search.get("to") ?? new Date().toISOString()).slice(0, 10),
  });
  const query: UsageAnalyticsQuery = { from: `${range.from}T00:00:00.000Z`, to: `${range.to}T23:59:59.999Z`, limit: 50 };
  const analytics = useResource(`analytics:${tenantId}:${query.from}:${query.to}`, async () => client ? client.usageAnalytics(tenantId, query) : demoAnalytics(config.usageDashboards.find((item) => item.tenantId === tenantId)), null as any);
  const requests = useResource(`requests:${tenantId}:${query.from}:${query.to}`, async () => client && view === "requests" ? client.usageRequests(tenantId, query) : null, null as any);
  const savedViews = useResource(`analytics-views:${tenantId}`, async () => client && view === "reports" ? client.savedAnalyticsViews(tenantId) : [], [] as any[]);
  const [detail, setDetail] = React.useState<UsageRequestDetail | null>(null);

  function update(nextView: View, nextRange = range) {
    setView(nextView); setRange(nextRange);
    const params = new URLSearchParams(); params.set("view", nextView); params.set("from", `${nextRange.from}T00:00:00.000Z`); params.set("to", `${nextRange.to}T23:59:59.999Z`);
    history.replaceState(null, "", `${location.pathname}?${params}`);
  }
  async function openRequest(requestId: string) { if (client) setDetail(await client.usageRequestDetail(tenantId, requestId)); }
  const data = analytics.data;

  return <ManagementPage title="Analytics" description="Operational billed usage, adoption, performance, request attribution, and explainable anomalies." eyebrow="Finance" actions={permissions.includes("usage:export") ? <Button variant="secondary" disabled={!client} onClick={() => client?.exportUsageCsv(tenantId, query).then((csv) => download(csv, "organization-usage.csv"))}><Download />Export CSV</Button> : null}>
    <Toolbar><div className="mgmt-segmented" role="tablist" aria-label="Analytics view">{VIEWS.map((item) => <Button key={item} variant="ghost" role="tab" aria-selected={view === item} onClick={() => update(item)}>{label(item)}</Button>)}</div><div className="mgmt-date-range"><label>From<Input type="date" value={range.from} onChange={(event) => update(view, { ...range, from: event.currentTarget.value })} /></label><label>To<Input type="date" value={range.to} onChange={(event) => update(view, { ...range, to: event.currentTarget.value })} /></label></div></Toolbar>
    <AsyncState loading={analytics.loading} error={analytics.error} onRetry={analytics.retry} empty={!data || data.totals.requests === 0} emptyTitle="No usage in this period">
      {data ? <>
        <MetricGrid items={[{ label: "Billed spend", value: formatMoney(data.totals.billedCostMicros) }, { label: "Requests", value: formatNumber(data.totals.requests) }, { label: "Tokens", value: formatNumber(data.totals.tokens) }, { label: "Success rate", value: data.totals.successRate == null ? "—" : `${Math.round(data.totals.successRate * 100)}%`, status: (data.totals.successRate ?? 1) < .9 ? "warning" : "good" }]} />
        {data.unavailableDimensions.length ? <p className="mgmt-callout" role="status">Partially unavailable: {data.unavailableDimensions.map(label).join(", ")}.</p> : null}
        {data.anomalies.length ? <Section title="Needs attention" description="Each anomaly compares the observed value with its stated baseline.">{data.anomalies.map((item: any) => <article className="mgmt-anomaly" key={item.id}><StatusPill tone={item.severity === "error" ? "danger" : "warning"}>{item.severity}</StatusPill><div><b>{item.label}</b><p>{item.explanation}</p><small>Baseline {item.baseline} · observed {item.observed} {item.unit} · {item.dimension.label}</small></div></article>)}</Section> : null}
        {view === "overview" ? <><Section title="Spend and request trend"><DualTrend label="Billed spend" points={data.series.map((point: any) => ({ label: point.ts.slice(0, 10), spend: Number(point.billedCostMicros) / 1e6, requests: Number(point.requests ?? 0) }))} spendFormat={(value) => formatMoney(value * 1e6)} /></Section><Breakdown title="Top departments" rows={data.breakdowns.departments ?? []} /><Breakdown title="Top members" rows={data.breakdowns.members ?? data.breakdowns.users ?? []} /></> : null}
        {view === "people" ? <><Breakdown title="People" rows={data.breakdowns.members ?? data.breakdowns.users ?? []} /><Breakdown title="Departments" rows={data.breakdowns.departments ?? []} /></> : null}
        {view === "models" ? <><Breakdown title="Models" rows={data.breakdowns.models ?? []} performance /><Breakdown title="Features" rows={data.breakdowns.features ?? []} performance /><Section title="Performance"><MetricGrid items={[{ label: "P50 latency", value: duration(data.performance.latencyP50Ms) }, { label: "P95 latency", value: duration(data.performance.latencyP95Ms) }, { label: "P50 TTFT", value: duration(data.performance.ttftP50Ms) }, { label: "Cached tokens", value: formatNumber(data.performance.cachedTokens) }]} /></Section></> : null}
        {view === "agents" ? <><Breakdown title="Agents" rows={data.breakdowns.agents ?? []} performance /><Breakdown title="Workspaces" rows={data.breakdowns.workspaces ?? []} /><Section title="Sandbox activity"><MetricGrid items={[{ label: "Sandbox minutes", value: formatNumber(Math.round(data.performance.sandboxMinutes)) }, { label: "Attributed requests", value: formatNumber((data.breakdowns.agents ?? []).reduce((sum: number, row: any) => sum + row.requests, 0)) }]} /></Section></> : null}
        {view === "requests" ? <AsyncState loading={requests.loading} error={requests.error} onRetry={requests.retry} empty={!requests.data?.items.length}><DataTable label="Redacted request records" columns={["Time", "Request", "Feature", "Model", "Status", "Tokens", "Billed", "Latency", "Reservation"]} rows={(requests.data?.items ?? []).map((row: any) => [new Date(row.ts).toLocaleString(), <Button variant="ghost" className="mgmt-table-link" onClick={() => openRequest(row.requestId)}><b>{row.requestId}</b><small>{row.agentId ?? row.workspaceId ?? "Unattributed"}</small></Button>, row.feature, row.model ?? "—", <StatusPill tone={["completed", "success", "succeeded"].includes(row.status) ? "good" : "danger"}>{row.status}</StatusPill>, formatNumber(row.tokensIn + row.tokensOut), formatMoney(row.billedCostMicros), duration(row.latencyMs), row.reservationStatus ?? "—"])} /></AsyncState> : null}
        {view === "reports" ? <Section title="Saved analytic views" description="Schedules and delivery configuration live under Reports & alerts."><DataTable label="Saved views" columns={["Name", "Visibility", "Owner", "Updated"]} rows={savedViews.data.map((row: any) => [row.name, row.visibility, row.ownerUserId, new Date(row.updatedAt).toLocaleString()])} /></Section> : null}
      </> : null}
    </AsyncState>
    {detail ? <DetailDrawer title={detail.requestId} subtitle="Redacted request" onClose={() => setDetail(null)}>{<dl>{Object.entries(detail).filter(([key]) => !["safeMetadata"].includes(key)).map(([key, value]) => <div key={key}><dt>{label(key)}</dt><dd>{value == null ? "—" : String(value)}</dd></div>)}</dl>}<Section title="Safe metadata"><pre className="mgmt-code-block">{JSON.stringify(detail.safeMetadata, null, 2)}</pre></Section><p className="mgmt-callout">Prompts, responses, credentials, signatures, and unrestricted metadata are never returned by this endpoint.</p></DetailDrawer> : null}
  </ManagementPage>;
}

function Breakdown({ title, rows, performance = false }: { title: string; rows: any[]; performance?: boolean }) { return <Section title={title}><DataTable label={title} columns={[title.slice(0, -1), "Requests", "Tokens", "Billed", ...(performance ? ["Error rate", "P95 latency"] : [])]} rows={rows.map((row) => [row.label, formatNumber(row.requests), formatNumber(row.tokens), formatMoney(row.billedCostMicros), ...(performance ? [row.errorRate == null ? "—" : `${Math.round(row.errorRate * 100)}%`, duration(row.latencyP95Ms)] : [])])} /></Section>; }
function duration(value: number | null) { return value == null ? "—" : value < 1000 ? `${Math.round(value)} ms` : `${(value / 1000).toFixed(1)} s`; }
function label(value: string) { return value.replaceAll("_", " ").replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function download(value: string, name: string) { const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(new Blob([value], { type: "text/csv" })); anchor.download = name; anchor.click(); URL.revokeObjectURL(anchor.href); }
function demoAnalytics(dashboard: any) { if (!dashboard) return null; const row = (dimension: string, item: any) => ({ dimension, id: item[`${dimension}Id`] ?? item.model ?? item.feature ?? null, label: item.model ?? item.feature ?? item.userId ?? item.departmentId ?? "Unattributed", billedCostMicros: item.costBilledMicros, requests: item.requests, tokens: item.tokens, errorRate: null, latencyP50Ms: null, latencyP95Ms: null }); return { tenantId: dashboard.tenantId, from: dashboard.from, to: dashboard.to, totals: { billedCostMicros: dashboard.totals.costBilledMicros, requests: dashboard.totals.requests, tokens: dashboard.totals.tokensIn + dashboard.totals.tokensOut, successRate: null, projectedMonthEndMicros: dashboard.totals.costBilledMicros }, series: dashboard.burnDown.map((item: any) => ({ ts: `${item.date}T00:00:00.000Z`, billedCostMicros: item.costBilledMicros, requests: item.requests, tokens: 0, successes: item.requests, failures: 0 })), breakdowns: { models: dashboard.byModel.map((item: any) => row("model", item)), features: dashboard.byFeature.map((item: any) => row("feature", item)), users: dashboard.byUser.map((item: any) => row("user", item)), members: dashboard.byUser.map((item: any) => row("user", item)), departments: dashboard.byDepartment.map((item: any) => row("department", item)), agents: [], workspaces: [] }, performance: { latencyP50Ms: null, latencyP95Ms: null, ttftP50Ms: null, ttftP95Ms: null, cachedTokens: 0, sandboxMinutes: 0 }, anomalies: [], unavailableDimensions: ["agent attribution", "latency in demo data"] }; }
