import * as React from "react";
import { Plus } from "lucide-react";
import { AsyncState, Button, DataTable, FormSelect, Input, ManagementPage, Section, StatusPill, SuccessMessage, formatMoney } from "./management-primitives";
import { useResource, type ManagementScreenProps } from "./management-context";

export function PlatformOrganizationsScreen({ client, config }: ManagementScreenProps) {
  const resource = useResource("platform:organizations", async () => client ? client.platformOrganizations() : config.platformTenants.map((row) => ({ tenantId: row.id, name: row.name, slug: row.slug, lifecycle: row.lifecycle, deploymentMode: row.deploymentMode, region: row.region, hostname: row.hostname, plan: row.plan, seats: row.seats, monthlySpendMicros: row.monthlySpendMicros, prepaidBalanceMicros: "0", billingHealth: "demo", ssoHealth: "demo", updatedAt: row.updatedAt })), [] as any[]);
  const [open, setOpen] = React.useState(false);
  const [message, setMessage] = React.useState("");
  const [pending, setPending] = React.useState<string | null>(null);
  async function provision(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!client) return; const form = new FormData(event.currentTarget); await client.provisionPlatformOrganization({ name: String(form.get("name")), slug: String(form.get("slug")), deploymentMode: String(form.get("deployment")) as any, plan: String(form.get("plan")), region: String(form.get("region")) || null, auditNote: String(form.get("auditNote")), confirmation: true, idempotencyKey: crypto.randomUUID() }); setOpen(false); setMessage("Organization provisioned and recorded in the operator audit trail."); resource.retry(); }
  async function lifecycle(tenantId: string, next: "active" | "suspended") { if (!client) return; const note = window.prompt(`Audit note for ${next === "suspended" ? "suspending" : "reactivating"} this organization:`); if (!note || note.trim().length < 3) return; setPending(tenantId); try { await client.updatePlatformOrganizationLifecycle(tenantId, { lifecycle: next, auditNote: note, confirmation: true, idempotencyKey: crypto.randomUUID() }); setMessage(`Organization ${next === "suspended" ? "suspended" : "reactivated"}.`); resource.retry(); } finally { setPending(null); } }
  return <ManagementPage title="Organizations" description="Provision, inspect, suspend, and review deployment, billing, and SSO health across tenants." eyebrow="Platform operations" actions={<Button disabled={!client} onClick={() => setOpen(true)}><Plus />Provision organization</Button>}>
    {message ? <SuccessMessage>{message}</SuccessMessage> : null}
    {open ? <Section title="Provision organization" description="Provisioning creates an isolated tenant. It does not create platform access for organization administrators."><form className="mgmt-inline-form" onSubmit={provision}><label className="mgmt-field">Name<Input name="name" required /></label><label className="mgmt-field">Slug<Input name="slug" pattern="[a-z0-9-]+" required /></label><label className="mgmt-field">Deployment<FormSelect name="deployment" defaultValue="shared" options={[{ value: "shared", label: "Shared" }, { value: "dedicated", label: "Dedicated" }, { value: "selfhost", label: "Self-hosted" }]} /></label><label className="mgmt-field">Plan<Input name="plan" defaultValue="enterprise" required /></label><label className="mgmt-field">Region<Input name="region" placeholder="Deployment default" /></label><label className="mgmt-field mgmt-field-wide">Audit note<Input name="auditNote" minLength={3} required /></label><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button>Confirm provisioning</Button></form></Section> : null}
    <AsyncState loading={resource.loading} error={resource.error} onRetry={resource.retry} empty={resource.data.length === 0} emptyTitle="No organizations"><DataTable label="Platform organizations" columns={["Organization", "Lifecycle", "Deployment", "Region", "Seats", "Monthly spend", "Billing", "SSO", "Action"]} rows={resource.data.map((row: any) => [<span><b>{row.name}</b><small>{row.slug}</small></span>, <StatusPill tone={row.lifecycle === "active" ? "good" : "warning"}>{row.lifecycle}</StatusPill>, row.deploymentMode, row.region ?? "—", row.seats, formatMoney(row.monthlySpendMicros), row.billingHealth, row.ssoHealth, <Button variant={row.lifecycle === "active" ? "destructive" : "secondary"} disabled={pending === row.tenantId} onClick={() => lifecycle(row.tenantId, row.lifecycle === "active" ? "suspended" : "active")}>{row.lifecycle === "active" ? "Suspend" : "Reactivate"}</Button>])} /></AsyncState>
  </ManagementPage>;
}
